pipeline:
  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - b${DRONE_BUILD_NUMBER}-test
    when:
      event: push
      branch:
        exclude: master

  build_master:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_REPO_BRANCH}
    when:
      branch:
        include: [ master ]
      event: push
